
# Save as config.yaml

# Cloudflare authentication
cloudflare:
  email: 
  token: # visit https://dash.cloudflare.com/profile/api-tokens

# DNS Record to update
# The record is identified by:
#   id: ID of the DNS Record;
#   zone_id: Zone ID of the DNS Record
update_ip:
  - id: 
    zone_id: 
  - id: 
    zone_id: 